{% set name = "pylibtiff" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b23e751c0ed46a48433523755ab2fbaf405d9f88eced3358482ff5ded749de0c

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - libtiff <=4.6.0
    - setuptools
  run:
    - python
    - numpy
    - libtiff <=4.6.0

test:
  imports:
    - libtiff

about:
  home: https://github.com/pearu/pylibtiff
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyLibTiff a Python tiff library.
  dev_url: https://github.com/pearu/pylibtiff

extra:
  recipe-maintainers:
    - bgruening
    - djhoese
