{% set name = "libtiff" %}
{% set version = "0.4.2" %}

package:
  name: py{{ name }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/l/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b80660541bfc51309b22dd676bcc94a8d77324b00fba3d331b7f564775f17a6
  patches:
    # See https://github.com/pearu/pylibtiff/pull/128
    - ignore-4.3-headers.patch

build:
  number: 5
  script:
    - cp $RECIPE_DIR/tiff_h_4_1_0.py libtiff/tiff_h_4_1_0.py
    - cp $RECIPE_DIR/tiff_h_4_2_0.py libtiff/tiff_h_4_2_0.py
    - cp $RECIPE_DIR/tiff_h_4_3_0.py libtiff/tiff_h_4_3_0.py
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - libtiff <= 4.3.0
  run:
    - python
    - numpy
    - libtiff <= 4.3.0

test:
  imports:
    - libtiff

about:
  home: https://github.com/pearu/pylibtiff
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyLibTiff a Python tiff library.
  dev_url: https://github.com/pearu/pylibtiff

extra:
  recipe-maintainers:
    - bgruening
    - djhoese
